channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -e ../compas_fea2_opensees
  - compas_view2
  - qtpy
  
#  Reference :
# https://github.com/conda/conda/blob/4.7.11/tests/conda_env/support/advanced-pip/environment.yml